### ISSUE TITLE
検出結果が全てtomatoになってしまう

### ISSUE THREAD

**Issue by Kanazawanaoaki** [Kanazawanaoaki/cook_eyes_coral#1]
学習を行った際のTensorBoardを見ると、上手く検出出来ているように見えるが、同じ画像をimage_publisherで出したものを認識させると全てtomatoとして検出されてしまう。  
TensorBoardの結果
<img width="739" alt="11981232478304" src="https://user-images.githubusercontent.com/38127823/82150160-ff0e5d00-9892-11ea-8312-757e7d5b2205.png">
rosのトピックの画像に対して物体検出を行った結果  
```
rosrun jsk_perception image_publisher.py _file_name:=/home/kanazawa/ros/jsk_demo_ws/src/cook_eyes/food_detector/food_only_data/try_dummy_later/train/382546.jpg 
```
![Screenshot from 2020-05-17 23-16-02](https://user-images.githubusercontent.com/38127823/82150889-9922d500-9894-11ea-99a9-42782aaf009b.png)

**Comment by knorth55** [comment]
これtensorboardのevalの画像では、それぞれ箱の色がちがうから別の野菜として認識されてるのかな
となるとedgetpuのほうの問題？
launchやlabelnames.txtが間違っていたりしないかな

**Comment by Kanazawanaoaki** [comment]
そうですね。evalの画像では正しくラベル付けもされているようなので、edgetpuの方の問題かなと思います。
launch (https://github.com/Kanazawanaoaki/cook_eyes_coral/blob/master/curry_detector_ros/launch/edgetpu_four_veg_detector.launch )
labels.txt  (https://github.com/Kanazawanaoaki/cook_eyes_coral/blob/master/curry_detector_ros/models/20200517-164047-try_dummy_later_dataset-from-dlbox/labels.txt )
を使用していて間違ってはいなさそうかなと思っています。  
image_publisherでトピックにする時に画質が落ちるために精度が落ちるなどもありえるのでしょうか？

**Comment by Kanazawanaoaki** [comment]
新しく、人やロボットの目線を意識してデータセットを作って見ましたが、
```
bash ./run.sh ./20200607-013746-vegs_v3_datasets/ tensorboard
```
で見られるTensorboardの可視化では検出できているのに、
<img width="1066" alt="12100792766441" src="https://user-images.githubusercontent.com/38127823/83959062-409f9000-a8b4-11ea-9199-80f7aa28b897.png">

ROSのimageトピックに対してedgetpuでの推論を行うと上手く行きませんでした。  
![Screenshot 2020-06-07 11:52:00](https://user-images.githubusercontent.com/38127823/83959224-55305800-a8b5-11ea-9a5f-e006ec0e061d.png)

↑は(https://drive.google.com/file/d/1ATHeIvae7YcE8Bw8tciWR0Lyhy5qL8_i/view?usp=sharing )の画像に対して行った、  

Coralのlaunchファイル実行(https://github.com/Kanazawanaoaki/cook_eyes_coral/blob/master/curry_detector_ros/launch/edgetpu_vegs_detector.launch )
```
roslaunch curry_detector_ros edgetpu_vegs_detector.launch INPUT_IMAGE:=/image_publisher/output
```
認識結果の可視化
```
rosrun image_view image_view image:=/edgetpu_object_detector/output/image
```
画像をrosのimageトピックにpublish
```
gdown https://drive.google.com/uc?id=1ATHeIvae7YcE8Bw8tciWR0Lyhy5qL8_i
rosrun jsk_perception image_publisher.py _file_name:=left0016.jpg
```

**Comment by knorth55** [comment]
案の定でした。
こちらのcommitで直っているはずです、すみません。
https://github.com/knorth55/coral_usb_ros/commit/4537370225c48a757da39f439cd6cd5a10c81ca8

あと精度はtensorflowのevaluationのそのままは出ないです。
なぜかというとcoral用に認識モデルを量子化しているからです。
TPUは確かint8のデータ型で動くために量子化されています（普通のGPU上ではFloat32）
興味があればこちらを: https://www.tensorflow.org/lite/performance/post_training_quantization

cc. @MiyabiTane, @mqcmd196

**Comment by Kanazawanaoaki** [comment]
ありがとうございます！  
やはりrgb問題だったんですね。上手く検出出来るようになりました。
![Screenshot from 2020-06-11 21-32-13](https://user-images.githubusercontent.com/38127823/84385891-4d611280-ac2b-11ea-989b-e6e39cfc7f0c.png)
